"""Add municipalities and reports

Revision ID: 0ea785ace380
Revises: 42791aedebf6
Create Date: 2026-05-18 13:40:33.476552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ea785ace380'
down_revision = '42791aedebf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('municipalities',
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('municipality_name', sa.String(length=100), nullable=False),
    sa.Column('municipality_address', sa.String(length=255), nullable=True),
    sa.Column('municipality_contact', sa.String(length=20), nullable=True),
    sa.Column('municipality_email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('municipality_id')
    )
    op.create_table('wards',
    sa.Column('ward_id', sa.Integer(), nullable=False),
    sa.Column('ward_number', sa.Integer(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.municipality_id'], ),
    sa.PrimaryKeyConstraint('ward_id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('municipality_name', sa.String(length=100), nullable=False),
    sa.Column('issue_description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.municipality_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('municipality_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('municipality_name', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'municipalities', ['municipality_id'], ['municipality_id'])

    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('municipality_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('municipality_name', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'municipalities', ['municipality_id'], ['municipality_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('municipality_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('municipality_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ward_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'wards', ['ward_id'], ['ward_id'])
        batch_op.create_foreign_key(None, 'municipalities', ['municipality_id'], ['municipality_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ward_id')
        batch_op.drop_column('municipality_id')
        batch_op.drop_column('municipality_name')

    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('municipality_name')
        batch_op.drop_column('municipality_id')

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('municipality_name')
        batch_op.drop_column('municipality_id')
        batch_op.drop_column('contact_number')

    op.drop_table('reports')
    op.drop_table('wards')
    op.drop_table('municipalities')
    # ### end Alembic commands ###
